### ISSUE TITLE
A bug in checking DF format

### ISSUE THREAD

**Issue by doctor-yes** [OwenYou/dftt_timecode#3]
in dftt_timecode\core.py line 90:

if mm % 10 != 0 and ff in (0, drop_per_min - 1): 

This is enforcing skip frame for every second which is incorrect, it should be only enforcing at the beginning of the minute. Suggest to change it to:

if mm % 10 != 0 and ss==00 and ff in (0, drop_per_min - 1):

**Comment by OwenYou** [comment]
Thanks for the comment, this bug is already fixed in #2.
: )
